# Generated by Django 5.2.6 on 2025-09-30 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
